### ISSUE TITLE
Cannot load a dataset with only compressed shards

### ISSUE THREAD

**Issue by nharada1** [mosaicml/streaming#138]
** Environment **

- OS: [Ubuntu 20.04]
- Hardware (GPU, or instance type): N/A

** To reproduce

1. Write an MDS dataset with zstd compression.
2. Delete the `*.mds` files.
3. Attempt to load the dataset via StreamingDataset.

## Expected behavior

The dataset is loaded correctly.

## Additional context

Instead of loading, the dataset hangs, suggesting that both the uncompressed and compressed files are required. This would mean I need to upload the entire dataset, both compressed and uncompressed, to S3.

**Comment by karan6181** [comment]
Hi @nharada1 , thanks for filing an issue. Once you generated an zstd compression shard files locally using [MDSWriter()](https://github.com/mosaicml/streaming/blob/main/streaming/base/format/mds/writer.py#L18), you can use the same shard files directory in [StreamingDataset()](https://github.com/mosaicml/streaming/blob/main/streaming/base/dataset.py#L92) object, the [StreamingDataset()](https://github.com/mosaicml/streaming/blob/main/streaming/base/dataset.py#L92) under the hood uncompress it for you, you don't need to do it manually. If you are streaming the dataset from a cloud, you just need to upload the compressed shard files to your S3 bucket (you don't need to upload uncompressed shard files to your S3 bucket), and as I mentioned above, the `StreamingDataset()` under the hood uncompress it for you in your `local` parameter directory.

**Comment by nharada1** [comment]
Hmmm okay I think the issue was that the local path should have been a separate temporary folder. I'm still seeing strange issues though, for example I'm seeing `IndexError: Relative sample index 16 is not present in the shard.00780.mds file.` which seems to be a batch size issue during data loading -- is the shard smaller than the batch? When I reduce the batch size it seems to work, although I do get a ton of warnings about not closing the shard files.

**Comment by nharada1** [comment]
Further debugging suggests that this is an issue with shuffling. Here is the code I'm using: https://github.com/nharada1/repro-mosaic-shuffle-issue

**Comment by knighton** [comment]
Can you include the code used to generate the streaming dataset that you used? That should help us figure out exactly what is happening, thanks!

Some things I noticed:

> 1. Write an MDS dataset with zstd compression. 2. Delete the *.mds files.

Unless I am not getting something, you should only be seeing `index.json` and sequentially numbered `#####.mds.zstd` files in the created dataset directory?

>  IndexError: Relative sample index 16 is not present in the shard.00780.mds file.

Offhand, this may indicate that a shard got truncated or overwritten, for example by overwriting different dataset splits to the same directory when creating the streaming dataset.

>  seems to be a batch size issue during data loading

(Elaborating in case this is helpful) A streaming dataset is a collection of shards strapped together. A shard is a collection of samples, which are available by random access. So an entire streaming dataset has random access, taking an absolute sample index. Within a shard, we call that offset a relative sample index. Batches can be composed out of samples from any shard(s) irrespective of their boundaries. So batch size and shard size don't interact. To debug what exact sample positions go into what batches (before shuffling), you can use `scripts/partition/web.py` or `scripts/partition/txt.py`.

> although I do get a ton of warnings about not closing the shard files

What warnings are you seeing exactly?

**Comment by nharada1** [comment]
Hey James,

Thanks for your help so far. I believe the issues I was seeing was from re-using my local directory on subsequent runs. I changed things to create a temporary folder instead each time the dataset is loaded and that seems to prevent the issues. Let me do a little more experimenting but if I can't find anything else I may close this issue.

**Comment by knighton** [comment]
Alright, well every ease of use feedback is appreciated!

Also note StreamingDataset has an argument `keep_zip` that may be relevant.

**Comment by nharada1** [comment]
I will go ahead and close this. I am having a lot of trouble getting mosaic streaming to work still with my workflow. I see that there's a community slack, but it says I need an @mosaicml.com email to sign up or to contact the admin. Is there a way I can access this slack workspace?

**Comment by knighton** [comment]
How about this link? https://join.slack.com/t/mosaicml-community/shared_invite/zt-1btms90mc-GipE2ufuPkKY0QBrmF3LSA

**Comment by nharada1** [comment]
That worked! I'll follow up there thank you!
