### ISSUE TITLE
No Python 3.11 support

### ISSUE THREAD

**Issue by nharada1** [mosaicml/streaming#144]
## Environment

- OS: [Ubuntu 20.04]
- Hardware (GPU, or instance type): N/A

## To reproduce

1. Create a conda environment with Python 3.11
2. Attempt to install either from pypi or HEAD (`pip install -e .`)

Result:

```sh
ERROR: Could not find a version that satisfies the requirement torchtext>=0.10 (from mosaicml-streaming) (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1, 0.4.0, 0.5.0, 0.6.0)
ERROR: No matching distribution found for torchtext>=0.10
```

## Expected behavior

Currently the latest version of Python is 3.11, but trying to install streaming with 3.11 causes dependency conflicts and will not install. 

## Additional context

Unsure if this is a bug or feature request.

**Comment by karan6181** [comment]
Thanks @nharada1 for raising an issue. Taking a look

**Comment by karan6181** [comment]
@nharada1 Are you blocked on using python 3.11 ? Or can you use python 3.10 ? We don't have an immediate plan to support python 3.11 since we want to ensure all the dependencies have the support for the same, however, we will do it soon!

**Comment by nharada1** [comment]
Not a blocker for me, I can use Py3.10 for now

**Comment by karan6181** [comment]
I am closing this issue for now. We will keep you posted once the Python 3.11 support is ready. Thanks!
