### ISSUE TITLE
Does MDS support GeoTiffs?

### ISSUE THREAD

**Issue by Geethen** [mosaicml/streaming#159]
## 🚀 Feature Request
If I were to encode a geotiff image with the mds format, when decoded would the spatial info of the image be retained?

## Motivation

It can be problematic if the geospatial information is dropped and difficult to reassign this information to each image patch. 

## Additional context

Perhaps a useful option would be to read/download image data from a large satellite image. Similar to the functionality provided by [torchgeo](https://torchgeo.readthedocs.io/en/stable/). However, I realise this may not be your target audience. Nevertheless, this functionality would be really beneficial to the geospatial community and the environmental challenges we work on :)

**Comment by knighton** [comment]
We have not encountered geotiff in our work yet. If your geotiff images can be pickled (presumably), then it will just work by setting your column type to `pkl` when writing the dataset.

Pickle on images can be wasteful of disk space. If you don't like the performance properties of pickle, you can also serialize your field yourself and save it as `bytes`, then deserialize it back yourself within your subclass of `StreamingDataset` in `__getitem__`. Or maybe this would be best served by using multiple fields (eg, image + spatial info), which is fine.

Please keep us updated if you are able to give the above a try, thanks!

**Comment by karan6181** [comment]
@Geethen Were you able to give it a try the suggestion provided by @knighton ?

**Comment by Geethen** [comment]
@Karan No I have not yet had a chance

**Comment by karan6181** [comment]
@Geethen Closing this issue for now. Please feel free to re-open if the suggestion provided by @knighton does not work for you. Thanks!
