### ISSUE TITLE
Integration with Jax?

### ISSUE THREAD

**Issue by rdilip** [mosaicml/streaming#172]
Hey guys,

Huge fan of the work you guys did with Composer, and was very excited to see this -- IMO fills a much needed whole on the data infra side.

I'm curious if it's recommended / if anyone's played around using this with Flax/JAX? I think the MDS is a nice solution to still having random access to sharded, serialized data (and sharded tfrecords + tf.Data is a pretty common stack). I know it's early days, but would love to know if anyone can warn me of any sharp edges / pitfalls ahead.

On a similar note, I'm not an expert in the PyTorch ecosystem, but as I understood the torch dataloaders have had issues keeping the GPUs fed. It looks like the recommended setup right now is to pass a StreamingDataset to a torch dataloader -- did you guys notice any issues related to the GPU usage?

Thanks!

**Comment by karan6181** [comment]
@rdilip Closing this issue for now. Please feel free to re-open in case your issue is not addressed. Thanks!
