### ISSUE TITLE
MDSWriter throws an error when writing to a local directory using Python 3.8

### ISSUE THREAD

**Issue by coders1122** [mosaicml/streaming#192]
## Environment
Python 3.8 (Kubeflow notebook)

- OS: [Ubuntu 20.04]
- Hardware (GPU, or instance type): N/A

## To reproduce

Script (copied from README):
`$ cat write_data.py`
```
import numpy as np
from PIL import Image
from streaming import MDSWriter

# Local or remote directory in which to store the compressed output files
data_dir = '/home/jovyan/tmp'

# A dictionary mapping input fields to their data types
columns = {
    'image': 'jpeg',
    'class': 'int'
}

# Shard compression, if any
compression = 'zstd'

# Save the samples as shards using MDSWriter
with MDSWriter(out=data_dir, columns=columns, compression=compression) as out:
    for i in range(10000):
        sample = {
            'image': Image.fromarray(np.random.randint(0, 256, (32, 32, 3), np.uint8)),
            'class': np.random.randint(10),
        }
        out.write(sample)
```

1. `python3 write_data.py`

## Expected behavior

I expect the data to be written successful to the local directory `./tmp` without any issues. I suspect this is an issue since the feature `cancel_futures` is only Python 3.9+. See [comment on PR](https://github.com/mosaicml/streaming/pull/171/files#r1133003652).

## Additional context

Error trace:
```
Traceback (most recent call last):
  File "write_data.py", line 24, in <module>
    out.write(sample)
  File "/home/jovyan/.local/lib/python3.8/site-packages/streaming/base/format/base/writer.py", line 265, in __exit__
    self.finish()
  File "/home/jovyan/.local/lib/python3.8/site-packages/streaming/base/format/base/writer.py", line 244, in finish
    self.executor.shutdown(wait=True, cancel_futures=False)
TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
```

**Comment by karan6181** [comment]
Hi @coders1122 , thanks for raising the issue. As you have mentioned, parameter `cancel_futures` is being added in Python 3.9 or later. Since, we are keeping `cancel_futures` as `False` anyhow which is also a default parameter in `shutdown()` method, we can remove the `cancel_futures` parameter from `self.executor.shutdown(wait=True, cancel_futures=False)`. Do you mind raising a PR with a fix since you have found out the issue? If you have a limited bandwidth, then I can also raise a PR. Thanks!

**Comment by coders1122** [comment]
I'm having troubles using multiple accounts (personal, corp) for Github on the same machine. Since it's quite trivial, mind setting the PR out for this instance?
Thank you for the quick response!

**Comment by karan6181** [comment]
The above PR has been merged. Closing this issue. Thank you for reporting it.
