### ISSUE TITLE
Questions about `StreamingDataset` in the case of limited (fast) local disk storage

### ISSUE THREAD

**Issue by VictorSanh** [mosaicml/streaming#213]
I have started to use the library and have enjoyed it so far! This is not a feature request but more a few questions to understand whether I am using the library correctly for what i need. Dumping these questions here as I believe some others would ask themselves the same question :)

I need to stream data from s3. My understanding is that the class will `StreamingDataset` will download the shards to the folder `local` and read from there.
- I have limited fast disk storage (like nvme disk). What happens if I iterate over all the shard samples? Is the shard nuked automatically? I am not sure I understand the argument `keep_raw` and more particularly what "epoch" means in this context.
- In the case `shuffle=False`, is there a way to pipe the data into the data preprocessing/training without writing that raw data on disk? I believe that's what WebDataset is doing. If the answer is yes, does that preserve the deterministic resuming?

Thanks in advance!

**Comment by knighton** [comment]
Thanks for trying us!

> I need to stream data from s3. My understanding is that the class will StreamingDataset will download the shards to the folder local and read from there.

Yes, happening in a thread that advances ahead of the currently yielded sample.

> I have limited fast disk storage (like nvme disk). What happens if I iterate over all the shard samples? Is the shard nuked automatically? I am not sure I understand the argument keep_raw and more particularly what "epoch" means in this context.

Historically, we have trained using StreamingDataset on dynamically scheduled nodes whose lifetime matches that of the training job, which have large fast local disk. This means that we didn't worry about leftover shards when training is done, or running of of space for shards.

As we grow, this assumption is no longer valid. We just recently added `keep_raw` in preparation for garbage collecting used shards, which will be added in an upcoming PR. When that is added, shards will be nuked automatically according to least recently used. Please hold tight for these updates to land!

> In the case shuffle=False, is there a way to pipe the data into the data preprocessing/training without writing that raw data on disk? I believe that's what WebDataset is doing. If the answer is yes, does that preserve the deterministic resuming?

Currently, we cache shards exclusively on disk, however there is nothing fundamentally preventing us from caching to shared memory instead if there is enough interest. Shard access is independent of sample ordering calculations.

**Comment by VictorSanh** [comment]
> As we grow, this assumption is no longer valid. We just recently added keep_raw in preparation for garbage collecting used shards, which will be added in an upcoming PR. When that is added, shards will be nuked automatically according to least recently used. Please hold tight for these updates to land!

Thanks for explaining, that makes sense! I'll keep an eye out :)

Closing this issue as I don't have follow up questions!
