### ISSUE TITLE
Shared dir selection method prone to collisions in concurrent scenarios

### ISSUE THREAD

**Issue by mx781** [mosaicml/streaming#217]
Hi and thanks for your work on the library! 

As you point out yourself in [`dataset.py:315`](https://github.com/mosaicml/streaming/blob/fe6eda31b73dabd7f7aec05aedaa49ac55315edb/streaming/base/dataset.py#L315), the shared directory should be unique per StreamingDataset to avoid shared dir collisions. However, the selection mechanism of try-the-same-one-first is prone to collisions under concurrent scenarios. Consider this:

```python
import multiprocessing

def run(i):
    bucket = "blah"
    path = "foo/bar/00000/"
    ds = streaming.StreamingDataset(
        remote=f"s3://{bucket}/{path}",
        local=f"/tmp/streaming/{bucket}/{path}",
        # shuffle_seed=i
    )
    return ds._shared_dir

with multiprocessing.Pool(4) as pool:
    results = pool.map(run, list(range(4)))
```

It _might_ work out fine, but more often than not, you get cryptic errors as below, presumably because of the time window between checking whether the dir exists and file-locking it.
```
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/streaming/base/shared.py", line 49, in __init__
    self._shm = SharedMemory(shm_path, True, size)
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 103, in __init__
    self._fd = _posixshmem.shm_open(
FileExistsError: [Errno 17] File exists: '/07196c_barrier'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/tmp/ipykernel_47575/4213878970.py", line 6, in run
    ds = streaming.StreamingDataset(
  File "/opt/venv/lib/python3.9/site-packages/streaming/base/dataset.py", line 252, in __init__
    self._worker_barrier = SharedBarrier(worker_barrier_filelock_path, worker_barrier_shm_path,
  File "/opt/venv/lib/python3.9/site-packages/streaming/base/shared.py", line 53, in __init__
    self._shm = SharedMemory(shm_path, False, size)
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 103, in __init__
    self._fd = _posixshmem.shm_open(
FileNotFoundError: [Errno 2] No such file or directory: '/07196c_barrier'
```

If the `# shuffle_seed=i` bit is uncommented, it works fine even with 64 parallel executions. While this workaround works fine for now, it took a while to trace down this behavior - wouldn't a better default be to seed deterministically based on the provided data path? If there's strong reasons not to change this, perhaps users should need to set `shuffle_seed` explicitly by default?

**Comment by karan6181** [comment]
Hi @mx781 , StreamingDataset expects same shared memory prefix when running on single node multi GPUs (one process per GPU) for communication between ranks (GPUs) and for that StreamingDataset relies on certain environment variables (WORLD_SIZE, LOCAL_WORLD_SIZE, RANK) to ensure that the shared memory only created by the leader local rank and then all the other ranks attaches to the same shared memory to ensure the correct behavior. When using multiprocessing pool without setting those variable might cause some unknown behavior. Have you give it a try running the `StreamingDataset` on multiple GPUs ?

**Comment by karan6181** [comment]
Another way is to provide some buffer time between two child process to ensure that the shared memory prefix creation doesn't collide. For example, something like this

```
import multiprocessing
import time
import os

import streaming

def run(i):
    s3_bucket = "blah"
    local_path = "/tmp/streaming/cifar10/"
    ds = streaming.StreamingDataset(
        remote=s3_bucket,
        local=os.path.join(local_path, str(i)),
        # shuffle_seed=i
    )
    return ds._shm_prefix

if __name__ == '__main__':
    tic = time.time()

    process_list = []
    for i in range(10):
        p =  multiprocessing.Process(target=run, args=[i])
        p.start()
        # Buffer time
        time.sleep(1)
        process_list.append(p)

    for process in process_list:
        process.join()

    toc = time.time()

    print('Done in {:.4f} seconds'.format(toc-tic))
```

**Comment by mx781** [comment]
Thanks for the reply! I forgot to mention that this occurs when using different datasets as well (because the seed is all the same for them). In such a case, you wouldn't expected the same shared memory block to be used across the workers, would you? 

The artificial delay works of course, as does forcing a different shuffling seed, but isn't there a deeper problem here of default behavior? There's nothing in the docs that suggest I couldn't or shouldn't use an MDS in the kind of scenario I described; if it's expected that `WORLD_SIZE`, `RANK` or any other env variable is set for expected behavior, then I guess an assertion should be made prior to creating the SHM block? Let me know if I've missed something in the docs that suggests this though!

**Comment by knighton** [comment]
Very cool! Sorry that we have been so busy. We will definitely look into it soon.

**Comment by karan6181** [comment]
Hi @mx781 , I have created a small example to demonstrate multiprocessing on CPU using `StreamingDataset` with some flag set and without any sleep between the process instantiation.

```python
import multiprocessing
import time
import os

import streaming

def run(i):
    s3_bucket = "blah"
    local_path = "/tmp/streaming/cifar10/"
    os.environ['RANK'] = str(i)
    ds = streaming.StreamingDataset(
        remote=s3_bucket,
        local=local_path,
    )
    # Do your work here
    time.sleep(2)
    return ds._shm_prefix

if __name__ == '__main__':
    num_process = 4
    os.environ['WORLD_SIZE'] = str(num_process)
    os.environ['LOCAL_WORLD_SIZE'] = str(num_process)
    # Local address
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    # use any open TCP port
    os.environ['MASTER_PORT'] = '33445'

    tic = time.time()
    
    with multiprocessing.Pool(num_process) as pool:
        results = pool.map(run, list(range(num_process)))

    toc = time.time()

    print('Done in {:.4f} seconds'.format(toc-tic)) 
```

We will improve our documentation to be very explicit about this. Thanks!

**Comment by karan6181** [comment]
@mx781 Closing this issue for now. Please let us know if you face any issue. Thanks!
