### ISSUE TITLE
Add py.typed marker file for type checking

### ISSUE THREAD

**Issue by micimize** [mosaicml/streaming#244]
`streaming` does not contain a `py.typed` file resulting in mypy errors:
![image](https://user-images.githubusercontent.com/8343799/234616737-3b70a6e0-0319-4a40-9e28-51ceeee3edf7.png)

As the package already uses type hints, all that needs to be done is add the empty marker file and ensure it's bundled in the published package: https://peps.python.org/pep-0561/#packaging-type-information

**Comment by karan6181** [comment]
Hi @micimize , can you please take a look at PR https://github.com/mosaicml/streaming/pull/245 when you get time? Thanks!
