### ISSUE TITLE
Is there an ETA for adding azure support?

### ISSUE THREAD

**Issue by njb-ms** [mosaicml/streaming#254]
I'm interested in trying this myself, but I'd need to use it with azure. Is there any ETA or outstanding blockers? Thanks!

**Comment by karan6181** [comment]
Thanks for showing your interest in Streaming. We have a Azure support in our roadmap but haven't prioritize it yet. If this is something that's blocking you, then we can take a look on how this can be added sooner. Additionally, If you are interested in a contribution then I can show you some pointers on where you need to make a change in a codebase to get this feature sooner. Please let us know. Thank You!

**Comment by njb-ms** [comment]
thanks, unfortunately this would block me using streaming as I'm tied to azure. If you have any pointers regarding what modifications would be needed please let me know! Thanks!

**Comment by karan6181** [comment]
Sure. Thanks for showing an interest in contribution. Let me share some pointers with you. As a background context, Streaming dataset uses cloud blob storage in two ways, first is to upload the shard files to a cloud blob storage and second is to download the same shard files from cloud blob storage during dataloader iteration or during model training. Right now, there are two different code path, one for upload and one for download. However, the changes would be similar for both. In future, we would like to combine those and make it a unified structure but that's a different discussion altogether. So, let me show you the places where you need to add your changes.

**Common**:

- You need to add a Azure python sdk dependencies (`azure-storage-blob`) which you can add in `setup.py` as part of [install_requires](https://github.com/mosaicml/streaming/blob/v0.4.1/setup.py#L44).

**Dowload**:

- All of the cloud blob storage support for download is in this [download.py](https://github.com/mosaicml/streaming/blob/main/streaming/base/storage/download.py) file.
- You need to add a method `download_from_azure` and call it inside [download_file()](https://github.com/mosaicml/streaming/blob/main/streaming/base/storage/download.py#L215) method.
- **Unit Test:** All the unit test for `download.py` is in [test_download.py](https://github.com/mosaicml/streaming/blob/v0.4.1/tests/test_download.py).

**Upload:**

- All of the cloud blob storage support for upload is in this [upload.py](https://github.com/mosaicml/streaming/blob/v0.4.1/streaming/base/storage/upload.py) file.
- You need to create a `class AzureUploader` which inherits from `CloudUploader` and provide the class name to [UPLOADERS](https://github.com/mosaicml/streaming/blob/v0.4.1/streaming/base/storage/upload.py#L20).
- **Unit Test:** All the unit test for `upload.py` is in [test_upload.py](https://github.com/mosaicml/streaming/blob/v0.4.1/tests/test_upload.py).

**Documentation:**

- You need to add the Azure support documentation [here](https://github.com/mosaicml/streaming/blob/v0.4.1/docs/source/how_to_guides/configure_cloud_storage_cred.md) on how user would setup credentials.



These might be too much of information for you but please let us know if you have any questions or doubt at any point. Thanks!

**Comment by njb-ms** [comment]
Thanks, try to find the time to try this out!

**Comment by karan6181** [comment]
Closing this issue as the Azure support is completed in PR https://github.com/mosaicml/streaming/pull/256. Please let us know if you see any issues. Thanks!
