### ISSUE TITLE
Documentation link to `pile.py` script for dataset conversion to MDS format returns 404 error

### ISSUE THREAD

**Issue by ouhenio** [mosaicml/streaming#257]
It looks like the [`pile.py`](https://github.com/mosaicml/stireaming/blob/main/streaming/text/convert/pile.py) script that is [referenced in the documentation](https://docs.mosaicml.com/projects/streaming/en/stable/how_to_guides/dataset_conversion_to_mds.html#pile) was moved somewhere else or is no longer available in the main branch.

Could it be possible to update the link and restore the accessibility to the script?

**Comment by ouhenio** [comment]
I just realized there is a typo in the link of your documentation. [Here](https://github.com/mosaicml/streaming/blob/main/streaming/text/convert/pile.py) is the correct one. 😊

**Comment by karan6181** [comment]
Thanks @ouhenio for identifying the issue. I have created PR https://github.com/mosaicml/streaming/pull/258 with the fix.

**Comment by ouhenio** [comment]
Damn, I made a PR too @karan6181. Do I drop it?

**Comment by karan6181** [comment]
Great! Let's merge your PR and I will close mine. Thank you for creating a PR. Appreciate it!

**Comment by ouhenio** [comment]
Glad to help, and thanks for you open source work. MosaicML has been very helpful. 😊
