### ISSUE TITLE
Composable datasets

### ISSUE THREAD

**Issue by jacobwjs** [mosaicml/streaming#271]
## 🚀 Feature Request

As a user, I'd like to easily compose and stream an (MDS, jsonl, etc) dataset from shard and index matched existing (MDS, jsonl, etc) datasets that reside in various buckets/folders

## Motivation

We want to train various models (generative, multi-modal) on large datasets (> 10T). One specific scenario is generating various embeddings with different models based on an original dataset.

e.g. `dataset_A` is an `(image, caption)` dataset. From `dataset_A` we generate embeddings from 10 different models and produce `embedding_1`, `embedding_2`, ..., `embedding_10` that are shard/index matched datasets to `dataset_A`.

We would like to be able to compose a streaming dataset from any combination of `dataset_A` and one or more of the embedding datasets. The composed dataset should respect the following,
- a batch from the composed dataset is shard/index matched between the composition (assuming they match)
- shuffle and streaming across multi-node/GPU maintains correspondence between composed datasets

We want to avoid creating a single dataset that includes all corresponding embeddings, which depending on the training scenario might cost large egress fees and disk space, while only a subset are used.

## [Optional] Implementation

Ideally some form of streams implementation assuming datasets have been created and stored in appropriate format(s),

e.g.
```
# compose datasets from various existing MDS datasets that are shard/index matching
composable_streams = [
  Stream(remote='s3://datasets/dataset_a'),
  Stream(remote='s3://datasets/embeddings_0'),
  Stream(remote='gcs://datasets/embeddings_3'),
]

dataset = StreamingDataset(
  composable_streams=composable_streams,
)
```

**Comment by jacobwjs** [comment]
Your community slack link seems unjoinable without a @mosaicml.com email btw

Would love to find some answers to questions regarding roadmap. Jumping on streaming at this point is a rather risky proposition given your MDS format. I believe this was mentioned by Rom in another thread.

How can one find a detailed overview of where streaming is heading?

**Comment by knighton** [comment]
Sorry about that! Here is a direct link: https://join.slack.com/t/mosaicml-community/shared_invite/zt-1vq08hfyp-u8YKlwq9ODXV7LnuiQhE6g

**Comment by karan6181** [comment]
Hi @jacobwjs, thanks for checking out Streaming dataset. Can you please let us know the incorrect slack link so that we fix it ? In the mean time, I will check myself offline too!

**Comment by knighton** [comment]
Also, how can we help de-risk your questions around MDS format?

Regarding stability, while StreamingDataset has evolved considerably under the hood, the underlying serialization format is unchanged from the initial PR last August (https://github.com/mosaicml/streaming/pull/2). Would a detailed spec be helpful?

As for the roadmap, in the near term we are mostly working on (a) dynamically evicting cold shards without degrading observed throughput, (b) parallel dataset conversion usability, and (c) streaming documentation. Your composable datasets suggestion is interesting and we are taking a look.

**Comment by jacobwjs** [comment]
> Also, how can we help de-risk your questions around MDS format?
> 
> Regarding stability, while StreamingDataset has evolved considerably under the hood, the underlying serialization format is unchanged from the initial PR last August (#2). Would a detailed spec be helpful?
> 
> As for the roadmap, in the near term we are mostly working on (a) dynamically evicting cold shards without degrading observed throughput, (b) parallel dataset conversion usability, and (c) streaming documentation. Your composable datasets suggestion is interesting and we are taking a look.

@knighton Thanks for your responses!

A detailed spec would be helpful, but my concern is a widely adopted spec. We like to be able to share expensive to produce data, and forcing others into MDS format could be an issue. But that's on our side to decide.

The biggest question is of course where this leads in the next 1+ year, interoperability with different tools and formats (Pandas, Parquet, etc.), and how this plays with various distributed training frameworks outside of MosaicML.

Features (a) and (b) sound great, and (c) definitely needs some love :)

Will close this out and hop on slack for further chats
