### ISSUE TITLE
Parallel writing of MDS files

### ISSUE THREAD

**Issue by mpetri** [mosaicml/streaming#288]
## 🚀 Feature Request

Parallel writing of MDS files (or define standard such that anybody can write a tool to write datasets)

## Motivation

I'm producing large datasets and currently I use:

```
    with MDSWriter(out=data_dir, columns=columns, compression=compression) as out:
        with open(args.input,"rb") as inf:
            dctx = zstandard.ZstdDecompressor()
            stream_reader  = dctx.stream_reader(inf)
            text_stream = io.TextIOWrapper(stream_reader, encoding='utf-8')
            for line in text_stream:
                triple_object = json.loads(line)
                out.write(triple_object)
                pbar.update(1)
```

but this single object writing is very slow. Is it possible to parallelize this somehow?

**Comment by karan6181** [comment]
Hi @mpetri , We have some [examples](https://github.com/mosaicml/streaming/blob/main/examples/multiprocess_dataset_conversion.ipynb) on how to achieve multiprocess dataset conversion. We are working towards make it more easy for the user. Please let me know if you have any feedback for us.

**Comment by karan6181** [comment]
Hi @mpetri , closing this issue since it is answered. Please let us know if you still have a question.
