### ISSUE TITLE
Timeout Error when local=None in StreamingDataset and training in distributed mode

### ISSUE THREAD

**Issue by vancoykendall** [mosaicml/streaming#293]
While trying to train with the llm-foundry repo on 1 node with 8 gpus, I kept getting a timeout error in all the non-leader processes when using a `StreamingDataset` I uploaded to s3. 

```
File "/usr/lib/python3/dist-packages/streaming/base/dataset.py", line 350, in __init__
    stream_shards = stream.get_shards(world)
  File "/usr/lib/python3/dist-packages/streaming/base/stream.py", line 387, in get_shards
    wait_for_file_to_exist(filename, TICK, 60,
  File "/usr/lib/python3/dist-packages/streaming/base/util.py", line 52, in wait_for_file_to_exist
    raise RuntimeError(f'{err_msg}, bailing out: ' + f'{timeout:.3f} < {dt:.3f} sec.')
RuntimeError: Index file /tmp/tmpqc4652dc/train/index.json took too long to download, bailing out: 60.000 < 60.003 sec.
```

In the training config, I don't set the `data_local` field, so when the `StreamingDataset` is initialized `local=None`. I found the tmp file where the index file is supposed to be downloaded and it exists and downloads in a second so it shouldn't be timing out. I went into the code and commented out the `RuntimeError` above so it would continue running and all the processes would try loading in the index file that definitely existed. This resulted in a new error: 
```
File "/usr/lib/python3/dist-packages/streaming/base/dataset.py", line 350, in __init__
    stream_shards = stream.get_shards(world)
  File "/usr/lib/python3/dist-packages/streaming/base/stream.py", line 392, in get_shards
    obj = json.load(open(filename))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp6uouofjr/train/index.json'
```
So it seems that since each process is setting the `local` attribute to a different tmp directory and then waits for the index file to be created in that directory, but it never will.

In `streaming/base/stream.py:100`
```python
self.local = local or mkdtemp()
```

**Comment by karan6181** [comment]
Hi @vancoykendall , thanks for your detailed explanation. You are right about each process is setting the `local` attribute to a different tmp directory and this causes the above error. This is indeed a bug and we will fix it soon! Wondering, do you have a fix proposal in mind or open to contribute ? Thanks!
