### ISSUE TITLE
Why can't I run two experiments in parallel which will load from the same dataset location?

### ISSUE THREAD

**Issue by eldarkurtic** [mosaicml/streaming#306]
I am trying to run two experiments in parallel (completely independent of each other) on the same server. Both are supposed to load data from the same location, but `StreamingTextDataset` is crashing with this error message:
```shell
Traceback (most recent call last):
  File "llm-foundry/train.py", line 442, in <module>
    main(cfg)
  File "llm-foundry/train.py", line 313, in main
    train_loader = build_dataloader(
  File "llm-foundry/train.py", line 72, in build_dataloader
    return build_text_dataloader(
  File "llm-foundry/llmfoundry/data/text_data.py", line 255, in build_text_dataloader
    dataset = StreamingTextDataset(
  File "llmfoundry/data/text_data.py", line 112, in __init__
    super().__init__(
  File "miniconda3/envs/sml/lib/python3.10/site-packages/streaming/base/dataset.py", line 325, in __init__
    self._shm_prefix, self._locals_shm = get_shm_prefix(my_locals, world)
  File "miniconda3/envs/sml/lib/python3.10/site-packages/streaming/base/shared.py", line 340, in get_shm_prefix
    raise ValueError(f'Reused local directory: {sorted(my_locals_set)} vs ' +
ValueError: Reused local directory: ['/nvmedisk/Datasets/llmfoundry/c4/train_small'] vs ['/nvmedisk/Datasets/llmfoundry/c4/train_small']. Provide a different one.
```

Both experiments are using this yaml config:
```yaml
train_loader:
  name: text  
  dataset:
    local: /nvmedisk/Datasets/llmfoundry/c4
    split: train_small
    shuffle: false
    max_seq_len: 2048
    decoder_only_format: true
  drop_last: true
  num_workers: 8
  pin_memory: false
  prefetch_factor: 2
  persistent_workers: false
  timeout: 0
```

**Comment by karan6181** [comment]
Hi @eldarkurtic , thanks for using streaming. The above error is intentional when the data fetches from the cloud since streaming uses shared memory for communication between ranks and it has to be unique plus no process clash should happen during shard downloading, and many other reasons. The same principle indirectly applied to a data which resides locally (remote=None). We will put some thought on how we can support multiple `StreamingDataset` instantiation using same `local` directory  and `remote=None`.

**Comment by eldarkurtic** [comment]
That would be a cool feature, especially for dealing with local datasets. My current hack is to "simulate" `remote` location as for example: `remote: /nvmedisk/Datasets/llmfoundry/c4` and then always use new `local` path (for example: `local: /nvmedisk/Datasets/llmfoundry/c4_duplicate1`) for each new experiment running in parallel. I assume there is no better way at the moment, because this approach consumes storage very quickly for large datasets?

**Comment by karan6181** [comment]
Yes, your approach looks good for now.

**Comment by tungdq212** [comment]
@karan6181 how about using `streaming.base.util.clean_stale_shared_memory()`. When I install `streaming` from source, I got same `Reused local directory` error with 2 local dataset, but `streaming` suggest me using `streaming.base.util.clean_stale_shared_memory()`. I add this line to code and it work. How does it help?

**Comment by karan6181** [comment]
Hi @eldarkurtic , I have captured your feature request and we will let you know once it is completed. For now, I am closing this issue since you have a workaround solution. Thank You!

**Comment by eldarkurtic** [comment]
@karan6181 thanks a lot, I really appreciate it!

**Comment by Riccorl** [comment]
Sorry if I comment on a closed issue, but I have a similar setup as OP. In multi-gpu setup (e.g., FSDP), two StreamingDataset can't have the same `local` path, as it translates to the second dataset to hang if used. Is there a way to share the local files between two datasets in the same "experiment"?
