### ISSUE TITLE
Can't load dataset from S3

### ISSUE THREAD

**Issue by germanjke** [mosaicml/streaming#310]
Hi! @karan6181 and others :)

I have some trouble with loading dataset from s3. It's interesting, that I can save my checkpoints to same s3

I'm launching `llm-foundry` pretrain configs, it looks like this:

```
data_local: #
data_remote: s3://my_bucket/path/to/data/my_dataset
```

I'm getting error

```
RuntimeError: Failed to download s3://my_bucket/path/to/data/my_dataset/train/index.json -> /tmp/tmp95xvpyl_/train/index.json. Got errors:
[ClientError('Object s3://my_bucket/path/to/data/my_dataset/train/index.json not found! Either check the bucket path or the bucket permission. If the bucket is a requester pays bucket, then provide the bucket name to the environment variable `MOSAICML_STREAMING_AWS_REQUESTER_PAYS`.'), ClientError('Objects3://my_bucket/path/to/data/my_dataset/train/index.json not found! Either check the bucket path or the bucket permission. If the bucket is a requester pays bucket, then provide the bucket name to the environment variable `MOSAICML_STREAMING_AWS_REQUESTER_PAYS`.'), ClientError('Object s3://my_bucket/path/to/data/my_dataset/train/index.json not found! Either check the bucket path or the bucket permission. If the bucket is a requester pays bucket, then provide the bucket name to the environment variable `MOSAICML_STREAMING_AWS_REQUESTER_PAYS`.')]
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
```

If I'm typing `aws s3 ls --endpoint-url MY_ENDPOINT_URL.com s3://my_bucket/path/to/data/my_dataset/train/index.json` I've got information about file, everything is OK

my exports before `composer train.py yaml.yaml`:

```
export AWS_ACCESS_KEY_ID="xxx"
export AWS_SECRET_ACCESS_KEY="xxx"
export S3_ENDPOINT_URL="MY_ENDPOINT_URL"
export AWS_S3_ENDPOINT="MY_ENDPOINT_URL"
export AWS_PROFILE="MY_PROFILE"
export AWS_DEFAULT_PROFILE="MY_PROFILE"
```

Do you have any ideas what's going wrong?

**Comment by karan6181** [comment]
Hi @germanjke , do you have a download permission ? Can you try below code if that works for you or not ? 

```
import boto3
from boto3.s3.transfer import TransferConfig
session = boto3.session.Session()
s3 = session.client('s3', endpoint_url=os.environ.get('S3_ENDPOINT_URL'))
s3.download_file('my_bucket', 'path/to/data/my_dataset/train/index.json', '/tmp/path/to/data/my_dataset/train/index.json', Config=TransferConfig(use_threads=False))
```

**Comment by germanjke** [comment]
Hi @karan6181 

yes following code works perfect

**Comment by germanjke** [comment]
yes true, same machine
it's look strange

**Comment by karan6181** [comment]
I think I know what is happening. Can you provide a `local` directory path to your yaml (such as `/tmp/data`) and try again?

**Comment by karan6181** [comment]
How many GPUs are you running this on ?

**Comment by germanjke** [comment]
8x A100

**Comment by karan6181** [comment]
Can you try running this on single GPU using `composer -n 1 train.py yaml.yaml` ?

**Comment by karan6181** [comment]
Streaming dataset creates a directory if does not exists. You see the above error since you ran the boto3 download_file() method directly. 

Are you on the [community slack channel](https://mosaicml.me/slack), if yes, then we can discuss the issue in detail over there since back and forth message here is not a great use of time. We can also post a summary here once it is resolved.

**Comment by germanjke** [comment]
> Streaming dataset creates a directory if does not exists. You see the above error since you ran the boto3 download_file() method directly.
> 
> Are you on the [community slack channel](https://mosaicml.me/slack), if yes, then we can discuss the issue in detail over there since back and forth message here is not a great use of time. We can also post a summary here once it is resolved.

done

**Comment by karan6181** [comment]
Summary: @germanjke was passing a custom S3 endpoint URL and streaming v0.4.1 did not had a support of exporting the `S3_ENDPOINT_URL` while downloading the files. Streaming [v0.5.0](https://github.com/mosaicml/streaming/releases/tag/v0.5.0) support this feature and after upgrading the streaming version to v0.5.0, user is not seeing the issue.
