### ISSUE TITLE
Question: what shuffle_block_size and cache_limit should I set for StreamingDataset? what size_limit should I set for MDSWriter?

### ISSUE THREAD

**Issue by whlzy** [mosaicml/streaming#334]
Thanks for this nice library!👏

This is not a feature request but more a few questions to understand: I believe some others would ask themselves the same question :)
1. what *shuffle_block_size* and *cache_limit* should I set for StreamingDataset?
2. what *size_limit* should I set for MDSWriter?

more specific
1. If my dataset size is 10TB and each file size is 10MB, how should I set these parameters: cache_limit, size_limit, shuffle_block_size? If the size of my data set is 10TB, and the size of each file is 10KB, how should I set these parameters: cache_limit, size_limit, shuffle_block_size?
2. Is there any guidance or best practices available to help me determine the appropriate values for these parameters?
3. Can I set the *cache_limit* here to be as small as 1GB, or it must need a large capacity such as 100GB.

Thanks in advance!😀

**Comment by knighton** [comment]
Example values:

`shuffle_block_size`: a million
`cache_limit`: available disk space
`size_limit`: 64mb

Shuffle block size is a tradeoff between how strong of a shuffle your stream(s) need for optimal convergence, and the number of shards that need to be resident to make progress. If you have a global pre-shuffle and not many epochs, it's needed less. If you are mixing multiple streams with different data distributions or upsampling stream(s) strongly, it's needed more.

The amount of data needed to be resident must be under cache_limit, or else the system will thrash. As it starts to thrash, throughput will drop precipitously. Data resident roughly scales with num_canonical_nodes * shuffle_block_size. Alternatively you could switch shuffling algorithms to not use shuffle_block_size, but may pay for it in convergence.

Shard size is a tradeoff of shard download latency, shard download throughput, shuffle quality (shuffling is aware of shard boundaries), etc.

**Comment by karan6181** [comment]
@whlzy Please let us know if you have more questions. We are working towards improving our documentation so that this things would be easier to understand. You can find some more information about some of the parameters that you have mentioned [here](https://docs.mosaicml.com/projects/streaming/en/stable/fundamentals/shuffling.html). Please let us know if you have more questions, otherwise, I will close this issue. Thank You!

**Comment by karan6181** [comment]
Closing this issue for now. Please feel free to re-open if you feel your issue is not addressed. Thanks!
