### ISSUE TITLE
Create index.json from set of mds shards

### ISSUE THREAD

**Issue by justinpinkney** [mosaicml/streaming#335]
Hello my index.json got deleted (or the MDSWriter failed to write it). Is there a way I can create this file from the list of .mds shards?

**Comment by justinpinkney** [comment]
update: it wasn't a failure of MDSWriter, just the user. But would still be useful to recreate index.json

**Comment by karan6181** [comment]
**Some background information:**
When converting the dataset into MDS format, the `index.json` is written last, having collected metadata about every shard in the dataset. If your dataset writing job crashes before completion for any reason, no `index.json`. Also, there is a high probability that your last shard is incomplete and including a partial data in the model training could be detrimental.

**Back to your question on is it possible to re-construct the index.json from shard files ?**
Yes, you can do that. Here are the steps:

The first four bytes of a MDS shard are the number of samples as a uint32.

To elaborate, MDS ("Mosaic Data Shard") format looks like this:
1. Number of samples in this shard: uint32
2. Size of each sample: array of uint32
3. JSON dict containing shard metadata (for recovering a lost index.json)
4. Sample data

Note that the MDSWriter metadata is stored in JSON from byte (4 + 4 * num_samples) to byte (offset of the first sample, which is found in bytes 4-8 of the shard). Of course, shards don't contain their own hashes, but most other fields are present. Unfortunately, we don't have a script for this yet.

**Comment by karan6181** [comment]
@justinpinkney Were you able to recreate the `index.json` file ?

**Comment by justinpinkney** [comment]
Thanks for the info that's super helpful. In the end with computer time being much cheaper than programmer time I just ran my conversion script again as a workaround 😊

**Comment by karan6181** [comment]
Great to hear that! Closing this issue then !
