### ISSUE TITLE
Using Streaming Dataset for Multi Node DDP

### ISSUE THREAD

**Issue by Srini-98** [mosaicml/streaming#337]
Hi,

I am running a multi node job with the complete mosaic stack. I have the entire dataset stored locally(in .MDS Format). The datasets need to be mixed and therefore I have a separate stream for each sub dataset(the path is passed as 'local' parameter with 'remote' set to none) with a proportion value set. When I start the job on one node the entire training loop works perfectly. When I move it a multi node training job I get the following error:

ValueError: Reused local directory: [All the paths to the dataset].

I faced this issue even when restarting a job on one node. When I just changed the folder name it worked(I got this off another issue) - [306](https://github.com/mosaicml/streaming/issues/306)  But in a multi node setup this fails. If you can let me know what I am doing wrong or if there is a fix for this , I would Appreciate it.

Thanks,

Srinivasan Nandakumar

**Comment by sysu-cxz** [comment]
When you trying to rerun a train may meet a problem like "ValueError: Reused local directory:[path] vs [path]. Provide a different one.", just delete the files which you created in /dev/shm/ would help.
