### ISSUE TITLE
mixing dataset, get the dataset name

### ISSUE THREAD

**Issue by gongbudaizhe** [mosaicml/streaming#344]
Hi, after mixing multiple dataset using streams, is it possible to get the dataset name where the data point is sampled?

**Comment by knighton** [comment]
If you have `sample_id`:

```
shard_id, shard_sample_id = dataset.spanner[sample_id]
stream_id = dataset.stream_per_shard[shard_id]
stream = dataset.streams[stream_id]
print(stream.remote)
```

**Comment by karan6181** [comment]
Hi @gongbudaizhe , closing this issue assuming it solves the issue that you requested for. Please feel free to re-open otherwise.
