### ISSUE TITLE
json.decoder.JSONDecodeError: Index file is empty or corrupted

### ISSUE THREAD

**Issue by shivshandilya** [mosaicml/streaming#345]
the following changes(as per PR #330) cause the following error on a single node, multi-gpu setup(4 gpus):
https://github.com/mosaicml/streaming/blob/4f02aeb50777370984994a34b9acf167a5883029/streaming/base/stream.py#L424
```
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Index file at /tmp/local_path_1/train/index.json is empty or corrupted. Expecting value: line 1 column 1 (char 0)
```

On re -running the script the issue is fixed. But every time I change the `local` path, it always gives this error in the first run and fixes itself from the second run. I tried running with the earlier code and the code runs fine every time. What could be the reason? Why was this here in the first place? I mean the downloading and renaming part. @karan6181 @knighton

_Originally posted by @shivshandilya in https://github.com/mosaicml/streaming/pull/330#discussion_r1274118386_

**Comment by karan6181** [comment]
Hi @shivshandilya , thanks for raising an issue. The original solution was correct, meaning, downloading the `index.json` as a `*.tmp` file and then renaming it. The reason for doing that is one process downloads the `index.json` file and other processes waits for it to exists. Now, there is no way to know if the file is fully downloaded or it's being currently downloading. If it is partially downloaded (meaning still downloading), the other processes thinks that it is fully downloaded and tries to load the `index.json` file and this leads to the above error message. I hope this clears the confusion. I will create a new PR to fix this.
