### ISSUE TITLE
Request for more ways to divide shards besides  size_limit

### ISSUE THREAD

**Issue by luke-han** [mosaicml/streaming#350]
## 🚀 Feature Request
Currently, `size_limit` is the only way to divide `MDSWriter`'s shards.
It would be nice to add a way to set the total number of shards or set the number of items per shard.

## Motivation
I want to set the number of shards to be divided by the number of nodes.
If possible, it would be even better if I could set the number of items per shard to be roughly same. (refer [img2dataset](https://github.com/rom1504/img2dataset/blob/f0188aedb897f94eb0d39ccefba641174244b927/README.md?plain=1#L154))

**Comment by knighton** [comment]
> I want to set the number of shards to be divided by the number of nodes.

May we ask why? After downloading on the basis of shards, Streaming does everything else on the basis of exact samples. We elaborate on the different complementary approaches taken to achieve a good shuffle here: https://docs.mosaicml.com/projects/streaming/en/stable/fundamentals/shuffling.html#factors-to-consider. Streaming doesn't map shards to nodes per se.

**Comment by luke-han** [comment]
@knighton 
I missed that documentation, thanks for the comment.
