### ISSUE TITLE
how to write mds file parallel? or is it support multiple files?

### ISSUE THREAD

**Issue by Gustfh** [mosaicml/streaming#371]
## 🚀 Feature Request
for example, i want to use spark to write the files parallel

## Motivation
since the data is very large, i cant use one process to output the data.

**Comment by karan6181** [comment]
Hi @Gustfh, [here](https://docs.mosaicml.com/projects/streaming/en/stable/examples/multiprocess_dataset_conversion.html) is the jupyter notebook which shows how to write MDS file in parallel. As far as spark dataframe goes, [here](https://github.com/mosaicml/streaming/pull/363) the is WIP PR which takes delta lake file / parquet file / dataframe and convert into MDS format.

**Comment by karan6181** [comment]
Hi @Gustfh , closing this issue. Please feel free to re-open if you think your question is not answered. Thanks!
