### ISSUE TITLE
Better documentation for epoch_size

### ISSUE THREAD

**Issue by lorabit110** [mosaicml/streaming#380]
## 🚀 Feature Request
We should better document StreamingDataset's behavior on dealing with epoch_size. I was expecting to see the exact number of samples requested. However, it seems to only work properly when epoch_size is k*64. Later on, I realized that num_canonical_nodes needs to set for epoch_size to work properly. However, I spent a few hours on reading code and experimenting to figure this out. It would be great to mention this behavior in the epoch_size's docstring.

**Comment by karan6181** [comment]
Hi @lorabit110 , Can you please share more details on what is your number of samples, number of physical nodes, epoch size, number of canonical nodes, etc ?

**Comment by karan6181** [comment]
The default `num_canonical_nodes` is 64 * physical nodes, hence, when the dataset is super small, we pad the sample to ensure the sample space is divided equally between nodes/gpus/workers, etc. If your dataset is super small, then I would recommend to provide lower `num_canonical_nodes` or even 1. Also, len(dataset) returns the number of samples per rank and `dataset.size` returns the total number of samples.

**Comment by karan6181** [comment]
Hey @lorabit110, we have better defaults in our latest streaming, the `v0.7.2` version, and you won't see this issue again. Thank you for your feedback. Please let us know if you still see the problem. Thank You!
