### ISSUE TITLE
deadlock when process exits before end of epoch

### ISSUE THREAD

**Issue by acutkosky** [mosaicml/streaming#386]
## Environment

- OS: AlmaLinux 8.8
- Hardware (GPU, or instance type): no gpu

## To reproduce
1. take any StreamingDataset
2. create an iterator
3. do one iteration of the iterator, but do NOT finish an epoch.
4. try to exit the program.

The following script will deadlock on exit:
```python
from streaming import MDSWriter
from streaming import StreamingDataset

### generate a sample dataset...
# directory for a sample dataset
out_root = 'deadlock_data'

# A dictionary of input fields to an Encoder/Decoder type
columns = {
    'anumber': 'int'
}

# some sample data
samples = [
    {
        'anumber': 123123
    }
    for _ in range(1000)
]

# write out the sample data
print("writing data...")
with MDSWriter(out=out_root, columns=columns) as out:
    for sample in samples:
        out.write(sample)
### finished generating the sample dataset


print("creating dataset object...")
remote_dir = 'deadlock_data'
local_dir = 'local_cache'
dataset = StreamingDataset(remote=remote_dir, local_dir=local_dir, split=None)
i = iter(dataset)
print("accessing the iterator...")

print(next(i))

print("exiting...")

# process will now hang on exit...

```

## Expected behavior
The program should exit.

## Additional context
I believe this is caused by the threads spawned by the iterator (`_prepare_thread`  and `_ready_thread`) never exiting. When the interpreter exits, it waits for these threads and so will hang. One hack to fix it is to add the following:
```python
import threading
from streaming.base.dataset import _IterState
def kill_iterators(dataset):
    if hasattr(dataset, "_iterator"):
        with dataset._iterator._lock:
            if dataset._iterator._state == _IterState.ITERATING:
                dataset._iterator._state = _IterState.EXITING
threading._register_atexit(kill_iterators, dataset)
```
Note that we need to use `threading._register_atexit` rather than the `atexit` module because the code that waits on the threads happens before `atexit`. Also, it does not work to call `dataset._iterator.exit()` inside `kill_iterators` because this will wait for two threads to exit, which causes its own deadlock if the process has been forked because one fork will not have any threads to exit.

**Comment by karan6181** [comment]
Hi @acutkosky , thanks for finding out the bug. Not sure how much bandwidth do you have, but you can open a PR with the change, would love to review it. Thanks!

**Comment by asuglia-alana** [comment]
Thanks a lot @acutkosky. I was about to open a similar issue. Any ideas on the timeline for a bugfix? Seems pretty important to me!
