### ISSUE TITLE
Resuable local directory

### ISSUE THREAD

**Issue by luke-han** [mosaicml/streaming#401]
## 🚀 Feature Request
I'm getting the error `Reused local directory` when I open the path multiple times. Is there any way to treat local directory read-only like remote?

## Motivation
I mount high-speed NAS storage shared by my team and trying to use it as a `StreamingDataset(local=/data/path/to/mds, remote=None)`, but I am having `Reused local directory` error and it is the major issue to introduce mosaicml streaming instread of webdataset.

Note that the NAS storage is very fast, so copying shards to local disk using `StreamingDataset(local=/tmp/path/, remote=/data/path/to/mds)` will be much slower to iterate samples.

**Comment by karan6181** [comment]
Hi @luke-han , thanks for sharing your use-case. Streaming team would brainstorm the idea on how can this be supported. Stay tune for the update!!

**Comment by karan6181** [comment]
Hi @luke-han , can you try #406 PR to see if that solves your issue ?

**Comment by luke-han** [comment]
Hi @karan6181, it works as I expected! Thanks 😄

**Comment by karan6181** [comment]
Hi @luke-han , closing this issue since it is resolved now. Feel free to let us know if you see any issues.
