### ISSUE TITLE
StreamingDataset deadlocks when cache_limit is smaller than the size of the shards

### ISSUE THREAD

**Issue by Hubert-Bonisseur** [mosaicml/streaming#417]
## To reproduce_

1. Create a dataset with size_limit = 10Mb for instance
2. Load it with cache_limit = 1Mb for instance
3. Access the first item
```python
    dataset = StreamingDataset(local="cache", remote="path_to_remote",
                                  cache_limit="1Mb")
    i = iter(dataset)
    print("accessing the iterator...")
    print(next(i))
    print("exiting...")
```
Nothing will be printed after "accessing the iterator..."
## Expected behavior
An error message should tell the user to increase the cache_limit

**Comment by karan6181** [comment]
Hi @Hubert-Bonisseur , thanks for filing the issue. We would fix this soon!
