### ISSUE TITLE
Does the `shuffle` arg on the dataloader do anything?

### ISSUE THREAD

**Issue by genesis-jamin** [mosaicml/streaming#419]
I noticed that `StreamingDataset` accepts arguments to control shuffling. Given this, does the shuffle arg on the dataloader do anything, or is it redundant if all shuffling is done by the dataset?

**Comment by karan6181** [comment]
Streaming Dataset is an Iterable style dataset, hence, the order of the sample is controlled by the Iterable style Dataset and not via Torch DataLoader unlike Map style dataset. If you try to use `shuffle=True` in Dataloader, you will see an exception `ValueError: DataLoader with IterableDataset: expected unspecified shuffle option`.

**Comment by genesis-jamin** [comment]
Got it, thanks!
