### ISSUE TITLE
How to enable mid-epoch resumption?

### ISSUE THREAD

**Issue by genesis-jamin** [mosaicml/streaming#421]
I see on the docs that deterministic mid-epoch resumption is one of the features offered by `streaming`, but the docs don't paint a clear picture of how to use this feature. Is there anything special I have to do to ensure this works? If it's relevant, I'm using pytorch lightning so all of my checkpointing logic is done through lightning. Thanks!

**Comment by karan6181** [comment]
Hi @genesis-jamin, we will update our documentation to include how to utilize mid-epoch resumption feature, but for now, you have to use [StreamingDataLoader](https://github.com/mosaicml/streaming/blob/main/streaming/base/dataloader.py#L16C7-L16C26) class which has `state_dict()` method which returns the streaming meta data as a dictionary, save it in a file or something. During resumption, call the `load_state_dict()` method which takes the dictionary which you saved in the previous step and it sets the appropriate state variables to ensure it resumes at a right location.
