### ISSUE TITLE
Total number of samples when using Streams with proportion?

### ISSUE THREAD

**Issue by genesis-jamin** [mosaicml/streaming#431]
Hello, the docs say the following about the `proportion` argument to `Stream`:

<img width="769" alt="image" src="https://github.com/mosaicml/streaming/assets/84467242/e8227b09-480f-481c-bb3e-99d7c7265320">

However `StreamingDataset` doesn't take in a `choose` argument. Should that be `epoch_size` instead?

**Comment by snarayan21** [comment]
Ah yes, good catch thank you!
