### ISSUE TITLE
A standard Batch type of Transformers is not handled by StreamingDataloader

### ISSUE THREAD

**Issue by Hubert-Bonisseur** [mosaicml/streaming#441]
## To reproduce

The function `_get_batch_size` of StreamingDataLoader handles batches of the type BatchEncoding from transformers. Nevertheless, the feature extractors for speech_recognition give batches of the type BatchFeature instead. In that case the function `_get_batch_size` crashes. 

I easily fixed this issue by inheriting StreamingDataloader (see below), but considering that BatchEncoding type is already handled by default, you may want to add this batch type, and maybe others from Transformers I don't know about.

```python
from transformers import BatchEncoding, BatchFeature

class CustomStreamingDataLoader(StreamingDataLoader):
    def _get_batch_size(self, batch: Any) -> int:
        """Get the number of samples in a batch.

        Args:
            batch (Any): The batch.

        Returns:
            int: Number of samples.
        """
        if isinstance(batch, (dict, BatchEncoding, BatchFeature)):
            for value in batch.values():
                return len(value)
            raise ValueError('Batch is empty')
        elif isinstance(batch, Tensor):
            return len(batch)
        else:
            return len(batch[0])

```

**Comment by snarayan21** [comment]
Hey, thanks for catching this! Would you mind submitting a small PR with this change? The change you have above looks good to me.
