### ISSUE TITLE
`get_partitions_orig` returns negative values when number of samples is low

### ISSUE THREAD

**Issue by antoinebrl** [mosaicml/streaming#460]
## Environment

- OS: MacOS
- Hardware (GPU, or instance type): CPU

## To reproduce

```python
>>> ids = get_partitions_orig(num_samples=2, num_canonical_nodes=64, num_physical_nodes=1, ranks_per_node=1, workers_per_rank=1, batch_size=1, drop_first=0)
>>> len(ids)
64
>>> ids
array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1])
```

## Expected behavior

I do not expect the `get_partitions_orig` to return negative values even when the number of samples is lower than the number of canonical nodes. The negative ids are filtered out which result in a `DataLoader` with a length of 33 (`batch_size=1`)

**Comment by karan6181** [comment]
Hi @antoinebrl, thanks for using Streaming Dataset. As you have discovered, the behavior is intentional when the number of samples is less than the number of canonical nodes because it divides the samples across nodes/GPUs/workers and we had to add some padding to make it divisible. The solution here is to use `num_canonical_nodes=1`. We are working toward better streaming dataset defaults so that such issues won't occur in the future.

**Comment by karan6181** [comment]
Hi @antoinebrl, does `num_canonical_nodes=1` solve your issue? In the mean time, we will update the defaults to a better value.

**Comment by antoinebrl** [comment]
Hi @karan6181, Thanks for looking into better default values!
The fact that there are negative values is somewhat less surprising than the sampling between the two items. The first sample is represented 32 times while the second one is only present once.

**Comment by karan6181** [comment]
@antoinebrl We have modified the streaming defaults as part of `v0.7.0` and you should not see the above behavior. Can you please try out the latest version`0.7.1` and let us know your experience? Thanks!

**Comment by karan6181** [comment]
@antoinebrl closing the issue due to inactivity. Please feel free to re-open if you think this is still an issue.
