### ISSUE TITLE
Convert folder of aws s3 parquet to s3 mds

### ISSUE THREAD

**Issue by segalinc** [mosaicml/streaming#462]
Hello,

how can I convert a folder containing a series of parquet files to a streaming dataset all in S3?
is there any pointer I can look at for this? 

thank you

**Comment by XiaohanZhangCMU** [comment]
Can you share how many and what is the average size of the parquet files? Are they belonging to the same dataset?

**Comment by segalinc** [comment]
Yes they are for the same dataset and we have 15M files total across 100 buckets

**Comment by XiaohanZhangCMU** [comment]
There must be more efficient way for it, but on top of my mind, the following pipeline may work:
1. download a collection of parquet files from s3 ([download_file](https://github.com/mosaicml/streaming/blob/6b638518294f7338f7bb54e9bb529bfad8e5fa50/streaming/base/storage/download.py#L36))
2. read parqeuet files to spark dataframe and call [dataframeToMDS](https://github.com/mosaicml/streaming/blob/6b638518294f7338f7bb54e9bb529bfad8e5fa50/streaming/base/converters/dataframe_to_mds.py#L163)  where the "out" parameter is the output s3 bucket. set merge_index = False
3. manually merge all index files. (in the coming release, we plan to provide a merge index util function in streaming)

**Comment by karan6181** [comment]
@segalinc Did you get a chance to try out @XiaohanZhangCMU suggestions? Thanks!

**Comment by karan6181** [comment]
closing the issue due to inactivity. Please feel free to re-open if you think this is still an issue.
