### ISSUE TITLE
Request for more informative error messages when cache_limit is hit

### ISSUE THREAD

**Issue by thayes427** [mosaicml/streaming#475]
## Feature Request
Request for more informative error messages when the `cache_limit` is too low.

## Motivation
I've found that error messages are pretty unhelpful when the `cache_limit` is too low or `num_canonical_nodes` and/or `shuffle_block_size` is too high (i.e., we run out of space).

I have seen errors like the following:
```
  File "/admin/thayes/micromamba/envs/es/lib/python3.10/site-packages/streaming/base/array.py", line 90, in __getitem__
    return self.get_item(at)
  File "/admin/thayes/micromamba/envs/es/lib/python3.10/site-packages/streaming/base/dataset.py", line 1135, in get_item
    sample = shard[shard_sample_id]
  File "/admin/thayes/micromamba/envs/es/lib/python3.10/site-packages/streaming/base/array.py", line 90, in __getitem__
    return self.get_item(at)
  File "/admin/thayes/micromamba/envs/es/lib/python3.10/site-packages/streaming/base/format/base/reader.py", line 309, in get_item
    data = self.get_sample_data(idx)
  File "/admin/thayes/micromamba/envs/es/lib/python3.10/site-packages/streaming/base/format/mds/reader.py", line 126, in get_sample_data
    begin, end = np.frombuffer(pair, np.uint32)
ValueError: not enough values to unpack (expected 2, got 0)
```
Or
```
File "/admin/thayes/micromamba/envs/es/lib/python3.10/site-packages/streaming/base/dataset.py", line 1135, in get_item
    sample = shard[shard_sample_id]
  File "/admin/thayes/micromamba/envs/es/lib/python3.10/site-packages/streaming/base/array.py", line 90, in __getitem__
    return self.get_item(at)
  File "/admin/thayes/micromamba/envs/es/lib/python3.10/site-packages/streaming/base/format/base/reader.py", line 309, in get_item
    data = self.get_sample_data(idx)
  File "/admin/thayes/micromamba/envs/es/lib/python3.10/site-packages/streaming/base/format/mds/reader.py", line 130, in get_sample_data
    raise IndexError(
IndexError: Relative sample index 857 is not present in the 9850/shard.00006.mds file.
```

**Comment by karan6181** [comment]
Hi, @thayes427, thanks for sharing your concern. Could you please share the streaming dataset hyperparameters that you were using along with the total dataset size and total number of samples? We will definitely improve the error messages so that it is easy to understand.

**Comment by thayes427** [comment]
Sure thing @karan6181 !

The size of each dataset is:
dataset1: 190560 samples, 6GB
dataset2: 33M samples, 590GB
dataset3: 74M samples, 220GB

```
dataset:
    streams:
      dataset1:
        ...
        proportion: 0.01
      dataset2:
        ...
        proportion: 0.49
      dataset3:
        ...
        proportion: 0.5
    shuffle: true
    num_canonical_nodes: 32
    predownload: 1_000
    cache_limit: 120gb
    shuffle_algo: py1br
    shuffle_block_size: 500000
```

**Comment by karan6181** [comment]
@thayes427 Interesting! Thanks for sharing the data points. Are you running it on four physical nodes? Also, what is the `cache_limit` that you are providing? 

I would highly encourage trying out [streaming simulator](https://docs.mosaicml.com/projects/streaming/en/stable/fundamentals/simulator.html), which runs a simulator based on the parameters that you have provided, and it will also give you an idea of good streaming default along with `cache_limit.`

**Comment by karan6181** [comment]
@thayes427, can you please share the `num_physical_nodes` that you are using? The reason why it hung indefinitely is that when the streaming hyperparameter is not set correctly, such as `predownload` and `shuffle_block_size` streaming would end up downloading a huge set of shards to make progress, and that fills up the disk space (let say 120 GB), and then processes fights between downloading a new shard and evicting an old shard and hence a deadlock. I would highly encourage trying out [streaming simulator](https://docs.mosaicml.com/projects/streaming/en/stable/fundamentals/simulator.html), which runs a simulator based on the parameters that you have provided, and it will also give you an idea of good streaming default along with cache_limit.

**Comment by thayes427** [comment]
Hi @karan6181 , I apologize for the slow reply. I was using a cache limit of 120gb with 4 physical nodes. Your explanation makes sense to me! I'm excited to try using the streaming simulator. Transparently, because we are re-using the same datasets over and over, and because they are not that large, we have downloaded them to our cluster. However, as soon as we have a need for downloading shards, I will be sure to give the simulator a try. Thanks for your help!

**Comment by karan6181** [comment]
@thayes427 Thanks for the information. I am closing this issue for now, and please feel free to re-open it when you try the simulator and still see the issue. Thank You!
