### ISSUE TITLE
Change column name

### ISSUE THREAD

**Issue by kietna1809** [mosaicml/streaming#492]
I created my dataset using MDS Writer. The process took 5 days to finish. The problem here is when I re-check MDS file, I found out the column name in MDS file had named incorrect. For instance: the "caption_latents" column is actually attach to "latents_256" data. I know the code is still running if I change the key in data loader but is very tangled when another person read the code. Is there anyway to rename the column only.

**Comment by karan6181** [comment]
> The process took 5 days to finish

Curious about why it took 5 days? What is the size of your dataset? Are you aware of multi-process dataset conversion? You can find the Jupyter notebook links [here](https://docs.mosaicml.com/projects/streaming/en/stable/examples/multiprocess_dataset_conversion.html) and [here](https://docs.mosaicml.com/projects/streaming/en/stable/examples/spark_dataframe_to_MDS.html).

> I found out the column name in MDS file had named incorrect.

Did you name the column key wrongly? MDSWriter takes the sample in a dict with `key` as a column name and `value` as the data. 


> For instance: the "caption_latents" column is actually attach to "latents_256" data. I know the code is still running if I change the key in data loader but is very tangled when another person read the code. Is there anyway to rename the column only.

There are two ways to handle:
1. Inherit [StreamingDataset](https://github.com/mosaicml/streaming/blob/main/streaming/base/dataset.py#L170) and override the [__getitem__](https://github.com/mosaicml/streaming/blob/main/streaming/base/array.py#L78) item where you can change the key name.
2. A more complicated step is to re-write the dataset.
