### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker. 

### ISSUE THREAD

**Issue by yiyihum** [mosaicml/streaming#493]
## Environment

- OS: Ubuntu 20.04
- Hardware: A100*8

## Issue Description

During the training process, an unexpected bus error occurred. This error might be related to insufficient shared memory (shm).

## Steps to Reproduce

1. Set up the environment with Ubuntu 20.04 and A100*8 hardware.
2. Initialize the StreamingTextDataset with 1593 streams.
    other config:
```
        "shuffle": true,
        "max_seq_len": 2048,
        "predownload": 24,
        "keep_zip": true,
        "num_canonical_nodes": 4,
        "shuffle_block_size": 10000
```
3. Observe that the length of the dataloader is 5799232.
4. Start the training process.
5. The error occurs at the start of the training iteration.

## Error Message

The error message displayed is as follows:

```
train_iteration:   0%|          | 0/5799232 [00:00<?, ?it/s]
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
```

**Comment by karan6181** [comment]
Hi @yiyihum, thanks for filing an issue. Could you let me know if you're using a docker container? If so, you should increase the shared memory for the container, as it might be too low. Check out this [link](https://github.com/pytorch/pytorch#docker-image).

Also, just out of curiosity, why do you have 1593 streams? You can have one stream for one dataset. If you have multiple streams for one dataset, you can [use merge_index()](https://github.com/mosaicml/streaming/blob/main/streaming/base/util.py#L219) method to merge index.json from sub-directories into one.

**Comment by yiyihum** [comment]
@karan6181 Thanks a lot ^^. I have a lot of sub-directories because of my bad data preprocessing code.  I will try  merge_index() method to merge index.json at first.  I am using a docker container, but I have no permission to increase the shared memory of the server.
