### ISSUE TITLE
Is `StreamingDataset` compatible with Ray distributed training?

### ISSUE THREAD

**Issue by genesis-jamin** [mosaicml/streaming#503]
I saw the following comment in #332. Do you know if StreamingDataset is compatible with multi-node distributed training using Ray?

> Hi @shivshandilya , Streaming dataset is not fully compatible with the PyTorch Lightening, there are some limitations on how PyTorch Lightening spins up the processes. For PyTorch Lightening (PTL) with DDP or other distributed strategy, when user run a script with `python main.py --n_devices 8`, the main process runs the `main.py` script and when you call `trainer.fit()`, PTL creates a N-1 (7 in this case) more processes (for a total of N, including the original main process). This means that the dataset created on the main process is constructed before any distributed environment variables are set, and before the other processes are even launched. Streaming dataset also relies on certain environment variables to get set before any process instantiate the StreamingDataset, otherwise it will use the default value for non-distributed use-case. Those variables are WORLD_SIZE, LOCAL_WORLD_SIZE, and RANK. Also, when using different strategy such as ddp_fork and ddp_spawn, PTL doesn't expose the environment variables (WORLD_SIZE, LOCAL_WORLD_SIZE, and RANK) which makes it impossible for Streaming to know how to split the dataset across ranks and how to communicate locally via multiprocessing shared memory.
> 
> I would recommend to either use torchrun or composer launcher or other launcher which spins up the process similar to torchrun/composer and sets the above environment variables.

_Originally posted by @karan6181 in https://github.com/mosaicml/streaming/issues/332#issuecomment-1642311367_

**Comment by snarayan21** [comment]
Closing out this issue as it has been inactive for a while.

**Comment by anubhavparas** [comment]
Hi,
I am facing issues with **StreamingDataset** being used with **Ray distributed training**.
I am setting the environment variables (for each ray worker) before each worker initializes the StreamingDataset.
Its somethings like this:
```
for id in num_actors:
  set_env_vars.remote(id, args....)     # happens async

for id in num_actors:
  init_streamingDataset.remote(id, args....)     # happens async
```

also tried this:
```
for id in num_actors:
  set_and_init.remote(id, args....)     # happens async

set_and_init():
  set_env_vars(id, args....)
  init_streamingDataset(id, args....) 

```



I have also tried having a blocking call for the first (master or rank 0) actor, so that it can set and initialize everything. But things get stuck for WORLD_SIZE > 1.
Getting this error after it times out: 
```
torch.distributed.DistStoreError: Timed out after 601 seconds waiting for clients. 1/64 clients joined.
```
