### ISSUE TITLE
choose a subset of shards for dataloading

### ISSUE THREAD

**Issue by gongbudaizhe** [mosaicml/streaming#505]
In webdataset, it is possible to load a subset of shards via: gs://nvdata-ocropus-tess/ia1-{000000..000033}.tar

can we achieve similar functionality in streaming?

**Comment by karan6181** [comment]
Hi @gongbudaizhe, can you please share your use case in detail so we can understand your request and serve you better? Thanks!

**Comment by gongbudaizhe** [comment]
I need to study the effect of training with different number of training samples. Therefore, for each training setting, I need to use a subset of the whole training set.

**Comment by snarayan21** [comment]
Hey @gongbudaizhe, you can modify the `index.json` file to only use a subset of the whole dataset's shards. Each shard will have an entry in the `index.json` file so you can delete entries as you see fit to get differently-sized subsets. To get more complex subsets based on some other filter function, you'll likely have to rewrite the shards for that particular subset.

**Comment by gongbudaizhe** [comment]
I see. Thanks!
