### ISSUE TITLE
cache_limit decreases utilization 

### ISSUE THREAD

**Issue by germanjke** [mosaicml/streaming#507]
Hi!

I have a problem with cache_limit. I have a large dataset (more than 1 TB) that is located on a remote s3. If I set a limit, productivity and learning speed drops. Moreover, the lower the limit, the greater the drawdown. In this case, the limit works as it should: the node does not download more data than the limit at a given time. If I don’t set a limit, I’m satisfied with the performance, but this is how all the datasets are downloaded, and in multi-nodier mode it can take about an hour, which is a very long time. What could be the problem? Thank you. 
![cache1](https://github.com/mosaicml/streaming/assets/43114292/d70d055f-03be-420d-b96d-fad94824a871)
![cache2 (1)](https://github.com/mosaicml/streaming/assets/43114292/c82f390e-0a64-4421-9a92-d57fbcdd5ccb)

**Comment by karan6181** [comment]
@germanjke Did you get a chance to try out Simulator [(link)](https://docs.mosaicml.com/projects/streaming/en/stable/fundamentals/simulator.html)?

**Comment by germanjke** [comment]
Simulator is good, works fine and gives u min cache limit
