### ISSUE TITLE
different eval on different dataloader streams

### ISSUE THREAD

**Issue by germanjke** [mosaicml/streaming#510]
Hello! We can create different train_loaders and eval_loaders by adding different streams to them. The question is, is it possible to create an eval_loader in such a way that evaluation is done on different streams, i.e., eval on stream A, stream B, etc.?

**Comment by karan6181** [comment]
@germanjke  Based on this [slack thread](https://mosaicml-community.slack.com/archives/C04MQFP4J2Z/p1700605094420119), is your issue resolved?

**Comment by germanjke** [comment]
hi thanks yes
