### ISSUE TITLE
Proper cleanup after failed runs

### ISSUE THREAD

**Issue by eldarkurtic** [mosaicml/streaming#573]
Hello,
I am trying to reproduce some examples from llmfoundry repo (latest commit, installed from source with all dependencies). More specifically, I am playing with this pretraining example: https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/pretrain/gpt-neo-125m.yaml
So, it's C4 pretraining with the default dataloader config from the original yaml:
```yaml
# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    shuffle: true
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
  drop_last: true
  num_workers: 8
```
Streaming C4 dataset is stored locally on a disk.

The main problem I am facing in this setup is that whenever I am debugging something (i.e. starting and killing a bunch of dummy runs), at some point the training would stuck during init. More specifically, it would stop at this point:
```bash
******************************
Config:
composer_commit_hash: None
composer_version: 0.17.2
node_name: unknown because NODENAME environment variable not set
num_gpus_per_node: 8
num_nodes: 1
rank_zero_seed: 42
time/remaining_estimate_unit: hours

******************************
2024-01-23 17:39:15,796: rank0[54410][MainThread]: WARNING: streaming.base.dataset: Because `num_canonical_nodes` was not specified, and `shuffle_algo` is py1e, it will default to be equal to physical nodes. Prior to Streaming v0.7.0, `num_canonical_nodes` defaulted to 64 * physical nodes.
2024-01-23 17:39:15,796: rank0[54410][MainThread]: WARNING: streaming.base.dataset: Because `shuffle_block_size` was not specified, it will default to max(4_000_000 // num_canonical_nodes, 1 << 18) if num_canonical_nodes is not None, otherwise 262144. Prior to Streaming v0.7.0, `shuffle_block_size` defaulted to 262144.

[STOPS HERE INDEFINITELY]
[IN NORMAL CONDITIONS it would continue as] [Eval batch=1/332] Eval on eval data
``` 

The only way to fix this issue would be to reboot the server which becomes a huge inconvenience. After reboot, no hanging issue anymore and the training run proceeds normally.
I have tried a few things:
1. reduce num_workers to {0,1,2,3} <-- doesn't make any difference
2. set prefetch to None <--- doesn't work
3. run on a single GPU <--- works fine, but not usable
4. server reboot <---works fine, but very inconvenient to reboot often

Do you have any ideas on what to do to clean up Streaming processes or whatever is running in the background and making these runs to hang?

**Comment by karan6181** [comment]
Have you tried calling `streaming.base.util.clean_stale_shared_memory()` at the beginning of the main script? The streaming library utilizes shared memory to coordinate some things between processes on the same node. In the event that a run is killed and there isn't an opportunity for a graceful cleanup, some artifacts might be left in shared memory on a node, and the next run shows after-effect issues.

**Comment by eldarkurtic** [comment]
Thanks for the suggestion @karan6181 , I will definitely try it out and post an update here with results.

**Comment by eldarkurtic** [comment]
Hey @karan6181 , seems like the magic command `streaming.base.util.clean_stale_shared_memory()` does help. Thanks a lot!
