### ISSUE TITLE
Integrating MDS Streaming with HF Dataset Streaming

### ISSUE THREAD

**Issue by siddk** [mosaicml/streaming#633]
## 🚀 Feature Request

Hey folks - I've loved using `streaming` for some of my research in multimodal pretraining and robotics. One thing I'd love to support is first-class integration with HF Datasets (e.g., similar functionality to their [WebDataset Streaming Integration](https://huggingface.co/docs/hub/en/datasets-webdataset#streaming)). 

I've created an issue on HF Datasets [here](https://github.com/huggingface/datasets/issues/6736), and @lhoestq seems receptive to the idea. At a low-level, not sure about the best way to implement this support. Would pointers/to talk this through!

## Motivation

Mosaic Streaming from MDS is fantastic for large-scale, reproducible pretraining! For some of my larger datasets, supporting the ability to stream MDS shards stored on HF Datasets while training would be fantastic.

Thanks!

**Comment by lhoestq** [comment]
It would be nice to stream datasets from HF using Streaming, e.g. supporting [hf://](https://huggingface.co/docs/huggingface_hub/guides/hf_file_system) paths

**Comment by karan6181** [comment]
@lhoestq Would it be possible for the user to upload the MDS shard files in the [hf://](https://huggingface.co/docs/huggingface_hub/guides/hf_file_system) paths? Or is your ask to support the HF remote path with whatever underlying files it can contain, such as Parquet, JSONL, etc?

**Comment by siddk** [comment]
Just following up on this; @karan6181 @lhoestq -- my understanding is that the HF Hub exposes dataset repositories via an `fsspec` API: https://huggingface.co/docs/huggingface_hub/main/en/guides/hf_file_system

From the Mosaic Streaming perspective -- can I just upload MDS shards to a Hub repo, and use the corresponding `hf://` path as a drop-in replacement for an `s3://` path?

Basically @karan6181 -- trying to figure out what "S3-compatible object store" really means under the hood vs. what the HF Hub natively supports.

**Comment by karan6181** [comment]
> Just following up on this; @karan6181 @lhoestq -- my understanding is that the HF Hub exposes dataset repositories via an `fsspec` API: https://huggingface.co/docs/huggingface_hub/main/en/guides/hf_file_system
> 
> From the Mosaic Streaming perspective -- can I just upload MDS shards to a Hub repo, and use the corresponding `hf://` path as a drop-in replacement for an `s3://` path?
> 
> Basically @karan6181 -- trying to figure out what "S3-compatible object store" really means under the hood vs. what the HF Hub natively supports.

@siddk  It appears that the HF hub functions primarily as a cloud storage solution, accessible via the `hf://` prefix. Integrating HF hub support into the streaming dataset should be straightforward. Do you have the capacity to implement HF hub backend support in the streaming dataset? You can model your work on the structure outlined in the PRs at [https://github.com/mosaicml/streaming/pull/311](https://github.com/mosaicml/streaming/pull/311) and [https://github.com/mosaicml/streaming/pull/256](https://github.com/mosaicml/streaming/pull/256). Please let us know if you have any questions—we're here to assist you.

**Comment by siddk** [comment]
Hey @karan6181 -- I'm a bit swamped with upcoming paper deadlines right now, but would love to see this supported. I can try carving out time to work on things in a few weeks, but wouldn't mind your expert take on this. I think the broader HF community would really appreciate it as well!

**Comment by mvpatel2000** [comment]
Included in v0.8.0 release

**Comment by lhoestq** [comment]
Wow amazing ! are there some docs already on how to use it ?

Also let me know if you plan to share this on social media, I'll be happy to re-share with the community !

**Comment by snarayan21** [comment]
Hey @lhoestq, @orionw added support for storing MDS datasets in huggingface. The relevant section in the docs is [here](https://docs.mosaicml.com/projects/streaming/en/stable/how_to_guides/configure_cloud_storage_credentials.html#huggingface-datasets). Will ask internally about posting on socials!

@orionw provided this simple script which shows off the new functionality:
```
from streaming import StreamingDataset

# Create streaming dataset
dataset = StreamingDataset(remote="hf://datasets/orionweller/wikipedia_mds/", shuffle=False, split=None, batch_size=1)

# Let's see what's in it
for sample in dataset:
    text = sample['text']
    id = sample['id']
    print(f"Text: {text}")
    print(f"ID: {id}")
    break
```

**Comment by snarayan21** [comment]
@lhoestq we tweeted here: https://x.com/DbrxMosaicAI/status/1818407826852921833
thanks!
