### ISSUE TITLE
Bug that causes FileExistsError in shm

### ISSUE THREAD

**Issue by Shade5** [mosaicml/streaming#689]
## Environment
- OS: [Ubuntu 20.04]
- Hardware (GPU, or instance type): [H100] 8x

## To reproduce

1. Train on single node with 8 gpus

When creating shm per rank, [this](https://github.com/mosaicml/streaming/blob/main/streaming/base/shared/prefix.py#L109) function is used to get the prefix

But as it only checks if the file exists, it is possible for two workers to confirm that a file does not exist at the same time. Later, the first one creates the file, but the second one crashes because the file exists.

```
FileExistsError: [Errno 17] File exists: '/000006_locals'
```

**Comment by Shade5** [comment]
I think this is the reason for this issue https://github.com/mosaicml/streaming/issues/332

**Comment by snarayan21** [comment]
Hey @Shade5, could you share some more details about your distributed training setup? How are you launching the processes and which distributed launcher are you using? And are you setting environment variables for distributed training correctly? In issue #332, most users were able to resolve this by checking their distributed training setup and using the appropriate launchers.

If you have a repro script that we can use to debug, that would be great!

**Comment by snarayan21** [comment]
@Shade5 also, only the worker that is local leader on each node (aka worker with index 0) calls `_check_and_find_retrying` to get the appropriate prefix int. See [here](https://github.com/mosaicml/streaming/blob/3e4e9b0cdbae261c651e6b65af3a62977c551547/streaming/base/shared/prefix.py#L188)

**Comment by Shade5** [comment]
@snarayan21 thanks for your quick reply! Is only the local leader is supposed to create the shared memory with [shm = SharedMemory(name, True, len(data))](https://github.com/mosaicml/streaming/blob/3e4e9b0cdbae261c651e6b65af3a62977c551547/streaming/base/shared/prefix.py#L192) and the other workers are supposed to load the same one with [shm = SharedMemory(name, False)](https://github.com/mosaicml/streaming/blob/3e4e9b0cdbae261c651e6b65af3a62977c551547/streaming/base/shared/prefix.py#L203).

**Comment by Shade5** [comment]
I'm using lightning, But I have set these correctly. I'll try to make a simple script for you to try
![image](https://github.com/mosaicml/streaming/assets/13672946/c1aad5aa-b393-4d4b-8144-9121c7289248)

**Comment by Shade5** [comment]
Nevermind, It works after I made sure that there's only one local leader per node.
