### ISSUE TITLE
Using mosaicml streaming with accelerate ?

### ISSUE THREAD

**Issue by benihime91** [mosaicml/streaming#722]
Hi , how can i integrate mosaicml streaming with [huggingface-accelerate](https://github.com/huggingface/accelerate).

Normally with a stypical dataset and dataloader you would need to do
```python
data_loader = accelerator.prepare(data_loader)
```
and internally i think accelerate is wrapping the loader under a DistributedSampler of sorts.
Is this required when using mosaicml streaming dataset ? Or i can skip this step following this comment: https://github.com/mosaicml/streaming/issues/225#issuecomment-1510478052

My use case is for multi-gpu multi-node training.

**Comment by snarayan21** [comment]
Hey @benihime91, what was the solution here? We've had some folks ask about using hf accelerate so would be good to know so we can add to docs.

cc @XiaohanZhangCMU

**Comment by wangyanhui666** [comment]
i skip this wrapping step.

If wrapping the dataloader, will cause error.
https://github.com/mosaicml/streaming/issues/789#issuecomment-2405432617

**Comment by snarayan21** [comment]
Closing this out since not wrapping the dataloader seems to be the correct solution here.
