### ISSUE TITLE
Incorrect container name in download_from_azure

### ISSUE THREAD

**Issue by jaehwana2z** [mosaicml/streaming#727]
## Environment

- OS: Ubuntu 22.04

## To reproduce

1. remote_dir = azure://account_name.blob.core.windows.net/container_name/path/to/blob
2. dataset = StreamingDataset(local=local_dir, remote=remote_dir, batch_size=1, split=None, shuffle=True)

## Expected behavior

Line 295 of `download_from_azure` in `download.py` parses the url as follows: 

> blob_client = service.get_blob_client(container=obj.netloc, blob=obj.path.lstrip('/'))

where `obj.netloc == account_name.blob.core.windows.net` and `obj.path.lstrip('/') ==  container_name/path/to/blob` from the example path in step 1. above.

However, this is incorrect, because to properly download the blob, `container` should be `container_name` and `blob` should be `path/to/blob`. 

Fixing the line to 

>directories = obj.path.lstrip('/').split('/') 
>blob_client = service.get_blob_client(container=directories[0], blob='/'.join(directories[1:]))

solves the issue for me

**Comment by snarayan21** [comment]
@jaehwana2z Hey, thanks for flagging! Mind submitting a PR? We always welcome community improvements, and happy to review.
