### ISSUE TITLE
How to use with multi GPU training?

### ISSUE THREAD

**Issue by MaxxP0** [mosaicml/streaming#740]
Since i could not find any documentation how to do multi GPU training/ dataloading i will ask here.
when using the following dataset
```
class StreamData37(StreamingDataset):
    def __init__(self, shuffle: bool, batch_size: int, use_online_dataset: bool, rank: int, world_size: int):
        remote = "s3://bucket/"
        local = None

        super().__init__(remote=remote, local=local, shuffle=shuffle, batch_size=batch_size,  cache_limit="512mb", download_retry=3, download_timeout=60)
        self.transforms = transforms.Compose([
            transforms.Resize((256, 256)),
            transforms.ToTensor()
        ])

    def __getitem__(self, idx):
          sample = super().__getitem__(idx)
          image = Image.open(io.BytesIO(sample['image']))
          caption = sample['caption']
          return self.transforms(image), caption

                         
dataset = StreamData37(False, MICRO_BATCH_SIZE, use_online_dataset=True, rank=fabric.global_rank, world_size=fabric.world_size)

dataloader = StreamingDataLoader(dataset, batch_size=MICRO_BATCH_SIZE, num_workers=16)
```
i get this error
ValueError: Reused local directory: ['/tmp/31e2e930a4f34dcd7b91bdd397c87df4'] vs ['/tmp/31e2e930a4f34dcd7b91bdd397c87df4']. Provide a different one. If using a unique local directory, try deleting the local directory and call `streaming.base.util.clean_stale_shared_memory()` only once in your script to clean up the stale shared memory before instantiation of `StreamingDataset`.

and when mitigating this by doing local = f"tmp_{os.getpid()}" it downloads every file multiple times (times the number of GPUs) which is really inefficient. furthermore all GPUs recieve the same inputs.

**Comment by XiaohanZhangCMU** [comment]
reason it downloads multiple times is because os.getpid() created several folders for each process. 

You can either delete all the temporary folder in /tmp then rerun, or just set local = 'some local path'. Let me know what error you ran into after doing that.

**Comment by MaxxP0** [comment]
Thank you for your answer. The temporary folders are created by the current run so they dont exist before the run at all and therefore i still get the same ValueError: Reused local directory error.

**Comment by MaxxP0** [comment]
Got it to work by not using lightning Fabric but pure pytorch DDP

**Comment by djbyrne** [comment]
I am also having this issue, it seems like MosaicML is just not compatible with Pytorch Lightning Distributed?

**Comment by LostGeorge** [comment]
> I am also having this issue, it seems like MosaicML is just not compatible with Pytorch Lightning Distributed?

Seconding this. I was able to get things to look like they are working by using `torchrun` and changing many of the distributed settings, but the loss accumulation was giving nans and infs (single gpu did not have that issue).

Might be good to add a note about incompatibility in the FAQ somewhere.
