### ISSUE TITLE
Can't output Vector or Array spark types

### ISSUE THREAD

**Issue by elbamos** [mosaicml/streaming#757]
## Environment

Databricks

## To reproduce

1.  Start with a Spark data.frame
2.  Use the VectorAssembler to create a features vector column.
3.  Attempt to write the data.frame to MDS using MDSWriter or dataframe_to_mds

## Expected behavior

I expect to be able to persist the Vector in mds format as an ndarray, or some other type readily coercible into an ndarray. 

## Additional context

I'm re-raising the issue raised here: #736. There, it is explained by @XiaohanZhangCMU that 'ndarray is not supported because, as you have seen, Spark has no such data types as a "ndarray"'. This being the case, what is the correct way to output a Spark Vector to mds? 

Things I have tried: 
- I get equivalent errors when coercing the Vector to a Spark Array and then trying to write it as an ndarray or as bytes. 
- I do not see a way to convert the Vector into an ndarray on the Spark workers (i.e., without loading the entire dataset into driver memory).

**Comment by XiaohanZhangCMU** [comment]
@elbamos  What is your spark schema? please print it out and share.

We only support a subset of native spark data types, all listed [here](https://github.com/mosaicml/streaming/blob/0fc72665e9c20e1c53d036d09592b7335ae8ae9a/streaming/base/converters/dataframe_to_mds.py#L35)

If you are using SparkML, you probably need to define the encoding/decoding methods of your own to use MDSWrite. The supported mds encoding types are [here](  https://github.com/mosaicml/streaming/blob/0fc72665e9c20e1c53d036d09592b7335ae8ae9a/streaming/base/format/mds/encodings.py#L529)

Note: Spark array is not equal to numpy array.

**Comment by elbamos** [comment]
I have tried two different schemas: 
```
root
 |-- features: vector (nullable = true)
 |-- target: integer (nullable = true)
 |-- training_weight: double (nullable = true)
```

and 

```
root
 |-- features: array (nullable = false)
 |    |-- element: double (containsNull = false)
 |-- target: integer (nullable = true)
 |-- training_weight: double (nullable = true)
```

I note that in the page you linked, `ArrayType(DoubleType())` is one of the supported types, and should be coercible to `ndarray:float64`. However when I try to use the second schema above, I get this error: `ValueError: ndarray:float64 is not supported by MDSWriter`.  The only difference I can see is that in my schema, the Array elements are not nullable.

**Comment by elbamos** [comment]
Even with the Array elements nullable: 

```
root
 |-- features: array (nullable = true)
 |    |-- element: double (containsNull = true)
 |-- target: integer (nullable = true)
 |-- training_weight: double (nullable = true)
```

I get the same error.

**Comment by elbamos** [comment]
I see I'm running version 0.7.4 which doesn't have your commit from 4 months ago adding the ArrayType to the list of supported types... Let me try to upgrade...

**Comment by elbamos** [comment]
Upgrading to 0.8.0 and setting the ArrayType to nullable did fix the problem and make the mds writeable. Thank you for your help!

**Comment by XiaohanZhangCMU** [comment]
Good finding! Yes, Array(double) was added recently. Let us know if you run into any new issues.
