### ISSUE TITLE
Possible to bypass/re-download checksum mismatched shards?

### ISSUE THREAD

**Issue by huxuan** [mosaicml/streaming#759]
## 🚀 Feature Request

We have huge amount of shards and we occasionally encounter broken shards due to unkonwn reason, currently the training process will just broken. I wonder if there is any approach to bypass or re-download the shard in case of broken download.

## Motivation

Keep the training process more smooth and retry for more robustness.

**Comment by snarayan21** [comment]
Hey, so there is a `download_retry` arg to StreamingDataset you can specify, which will retry downloads a given number of times. It defaults to 2. There's a `download_timeout` arg too. The combination of these will let you be more tolerant to shard download failures. More info here: https://docs.mosaicml.com/projects/streaming/en/stable/dataset_configuration/shard_retrieval.html#retries-and-timeout

As for bypassing/skipping a shard download -- Streaming is purpose-built for deterministic, elastic training, and this means the sample order is precomputed/fixed. So we can't skip sample IDs that are needed for training. I'd make sure to check your dataset to make sure all shards exist.

Hope this helps!
