### ISSUE TITLE
Add 'concat' option in C4 dataset

### ISSUE THREAD

**Issue by ananyahjha93** [mosaicml/streaming#76]
## 🚀 Feature Request
Benchmark repo has 2 options for C4 dataset samples: concat and truncate.

For LM training, 'concat' seems to be the only correct way forward. Can the 'concat' option present in the StreamingC4 from the benchmark repo be added to this repo as well?

## Motivation

For LM training, using truncate instead of concat makes the training process redundant and the LM fails to learn anything.

![image](https://user-images.githubusercontent.com/7491256/201791679-49c1c5dd-b007-4df5-b300-f75799d71637.png)
<img width="811" alt="Screen Shot 2022-09-27 at 12 19 02 AM" src="https://user-images.githubusercontent.com/7491256/201791684-bc5a591d-f2f9-42d8-8cbb-5ca3bb992d66.png">

## Implementation

This works with the benchmark repo, not sure if this can directly be copied over here: https://github.com/mosaicml/benchmarks/blob/main/llm/src/data_c4.py

**Comment by ananyahjha93** [comment]
@abhi-mosaic

**Comment by karan6181** [comment]
Hi @ananyahjha93, thanks for the feature request. I have created a PR https://github.com/mosaicml/streaming/pull/77 to add that support. The full thorough testing is WIP and will let you know once it is merge. Thank You!

**Comment by karan6181** [comment]
Hi @ananyahjha93 , The above PR is merged. Let me know if you face any issues. Thank You!
