### ISSUE TITLE
Running into "FileExistsError: [Errno 17] File exists: '/000000_epoch_shape'" even with single GPU

### ISSUE THREAD

**Issue by deepanshu-a2z** [mosaicml/streaming#802]
## Environment
Running on docker instance with github checkout of streaming "3a6a5490678a2efa028ed96ba9b8813fba8687eb"
- OS: [Ubuntu 20.04]
- Hardware (GPU, or instance type): [A100]

## To reproduce

Creating PytorchLightning trainer object on a system with 1 GPU and 24 cpu nodes
```python
trainer = pl.Trainer(
        max_epochs=5,
        accelerator="gpu",
        precision="16-mixed",
        devices=-1,
        val_check_interval=0.3,
        callbacks=callbacks,
        fast_dev_run=config['running']['fast_dev_run']
)

trainer.fit(model, train_dataloader, val_dataloaders=eval_dataloader)
```

## Expected behavior
With num workers for dataloader at 4, it works seamlessly and the training loop progresses as expected.

## Additional context
When I increase the num_workers to 16 or beyond, I keep getting `"FileExistsError: [Errno 17] File exists: '/000000_epoch_shape'"`. Usually I was able to clear this issue by clearing streaming dirs or rebooting machine but now this even that has stopped working.

**Comment by deepanshu-a2z** [comment]
This seems to be unlike https://github.com/Lightning-AI/pytorch-lightning/issues/20226 or https://github.com/mosaicml/streaming/issues/767 since the issue seems to be present even without any distributed computing related configuration

**Comment by snarayan21** [comment]
Hey @deepanshu-a2z, this is likely due to shared memory files from previous failed runs. can you try running the following before your training run?

```
import streaming.base.util as util
util.clean_stale_shared_memory()
```

**Comment by deepanshu-a2z** [comment]
I am calling this function just before initializing the dataloader object, but it still seems to be causing issues. The issue seems to be a bit non-deterministic since it comes and goes.
For me some compute nodes seem to be seeing this error more often than others. Additionally I do not run into this error when the num workers is small (~4-6). 
Is there any scope that higher number of workers makes some race condition more likely?

**Comment by snarayan21** [comment]
@deepanshu-a2z How many nodes & gpus are you training with? It seems like you're calling the function in the right place -- just want to check that you're calling this before initializing the dataset and not just the dataloader.

How many workers are you using? Typically we find that increasing the dataloader num_workers beyond 8 does not give any performance benefits and can actually hurt you if the total number of workers (num_workers*gpus_per_node) exceeds the number of cpu cores. Is dataloading too slow with a lower number of workers? That logic is all unchanged from the pytorch side btw.

**Comment by deepanshu-a2z** [comment]
Yes that's correct I am calling `clean_stale_shared_memory` before dataset init.

The compute node I am working on has 24 cores and 1 GPU. I was getting error with 16 and 22 workers.
Dataloading requires downloading relatively large files from azure, so having larger number of worker nodes does translate to better GPU utilization for my case.

**Comment by snarayan21** [comment]
@deepanshu-a2z I see you're using pytorch lightning, how are you setting up & launching distributed training? Or since you're on 1 GPU, I'm assuming you don't need it?

I'm still wondering why you're seeing this error even after cleaning stale shared mem. Can you provide a small repro script we could use to debug?

**Comment by deepanshu-a2z** [comment]
I did not setup any distributed training config due to single GPU single node setup.

I moved cache to a faster disk on the VM (along with some other architecture changes), and I am not seeing the error. This might be coincidental, since the issue was not occurring deterministically for me.

**Comment by XiaohanZhangCMU** [comment]
Hi @deepanshu-a2z can you try the recent release 0.9.1 and see if the issue still exists?

**Comment by XiaohanZhangCMU** [comment]
@deepanshu-a2z closing this issue. if the error still keeps showing up on your end, please let me know.

**Comment by deepanshu-a2z** [comment]
Thanks a lot for looking into this error and apologies for the delayed response. 
I no longer run into that error, but I could not figure out if it was due to non-determinism of the error or it truly got eliminated.
