### ISSUE TITLE
Issue: NCCL ProcessGroup Device Mapping Bug when using streaming with accelerate

### ISSUE THREAD

**Issue by wangyanhui666** [mosaicml/streaming#807]
## Environment

- OS: [Ubuntu 20.04]
- Hardware (GPU, or instance type): [A100]

## To reproduce

1.Set up a distributed training pipeline using accelerate, to train a diffusion
2.Use the streaming dataset
3.Run the distributed training using NCCL backend on multiple GPUs.

warning:[rank1]:[W1018 11:57:38.174478138 ProcessGroupNCCL.cpp:4115] [PG ID 1 PG GUID 0 Rank 1]  using GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank2]:[W1018 11:57:38.183572992 ProcessGroupNCCL.cpp:4115] [PG ID 1 PG GUID 0 Rank 2]  using GPU 2 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id."

## Expected behavior
The devices should be correctly mapped for each rank, and the dist.barrier() call should execute without any issues.

## Additional context

It seems the issue arises from the device mapping in the distributed context when using streaming with accelerate. 
In streaming dataset use dist.barrier(). But accelerate use accelerator.wait_for_everyone() to sync.

however i add dist.init_process_group(backend='nccl') in my accelerate based code. Still have this warning.

The devices are not properly identified by NCCL when calling dist.barrier(). A potential solution could be to ensure device_ids are specified correctly when invoking dist.barrier(), or init_process_group() needs to properly associate rank with the correct GPU.

**Comment by XiaohanZhangCMU** [comment]
Hi @wangyanhui666 thank you for raising the issue! We haven't tested support for HF Accelerate, although we have seen increasing requests recently. 
Can you send us a minimal repro script with a pip freeze of the libraries you are using? Thanks!

**Comment by snarayan21** [comment]
@wangyanhui666 Hey, this isn't necessarily a problem with streaming code -- if you simply add a `torch.distributed.barrier()` call inside your training script, do these warnings also show? I've seen these before even when just using DDP on a plain pytorch model, and in my experience this has been harmless.

If you're seeing the same warnings with just `torch.distributed.barrier()` then it's particular to how you are setting up and launching distributed training and is not Streaming-specific.

**Comment by wangyanhui666** [comment]
Thanks for your reply. I think it might be a PyTorch version issue. I didn’t get this warning when using PyTorch 2.4, but I encountered it with PyTorch 2.5. And has not caused any training errors so far.

However, I have also organized the code I’m currently using with streaming and Accelerate. The repository is available at https://github.com/wangyanhui666/debug_streaming_accelerate. If you’re interested, you should be able to reproduce the warning. I’ve done an initial check, and the repository can successfully reproduce the bug. If you encounter any issues during the process, feel free to reach out to me for discussion.

**Comment by snarayan21** [comment]
Thanks @wangyanhui666 !
