### ISSUE TITLE
Simulation Relative import errors 

### ISSUE THREAD

**Issue by apd-smcclendon** [mosaicml/streaming#848]
## Environment
- OS: [Windows 10 Home ]
- Python version: 3.10.0

## To reproduce

1. pip install --upgrade "mosaicml-streaming[simulator]"
2. simulator

## Expected behavior

After initial installation during main command execution experienced multiple issues with relative import statements not working. After editing code from things like ```from core.sim_dataset import SimulationDataset``` to ```from simulation.core.sim_dataset import SimulationDataset``` I was able to get the simulator to run

**Comment by srstevenson** [comment]
I've a PR open to address this in https://github.com/mosaicml/streaming/pull/838

**Comment by ethantang-db** [comment]
PR https://github.com/mosaicml/streaming/pull/838 merged, closing issue
